name: ✨ Feature Request
description: Suggest a new feature
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like to solve this problem?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions have you considered?
      placeholder: "I've tried X, but it doesn't work because..."

  - type: dropdown
    id: use-case
    attributes:
      label: Primary Use Case
      description: What's the main context for this feature?
      options:
        - "General - Broad applicability"
        - "Safety-Critical - Life/safety systems"
        - "Military/Defense - Tactical operations"
        - "Compliance - Regulatory requirements"
        - "Developer - Development workflow"
        - "Performance - Speed/scale improvements"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Low - Nice to have"
        - "Medium - Improves workflow"
        - "High - Blocks production use"
        - "Critical - Safety requirement"
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to help implement this feature?
      options:
        - label: I am willing to submit a PR for this feature
        - label: I can help with testing this feature
        - label: I can provide domain expertise/requirements